# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
 
  build:
    runs-on: ubuntu-latest

    steps:


      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
        
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: Thrinadh-Kumpatla/deploy-repo
          token: ${{ secrets.GH_PAT }}
          path : deploy-repo
          
      - run: |
          ls
          cd deploy-repo
          cat README.md
          ls
          sed 's/2.0.0/3.0.0/g' README.md >> README1.md
          rm -rf README.md
          mv README1.md README.md
          ls
          cat README.md

      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PAT }}
          path : deploy-repo

#       - run: |
#           ls
#           pwd
 
#           cd /home/runner/work/build-repo/
#           ls
#           pwd


 

